### PR TITLE
Auto set the footer year

### PR DESCRIPTION
**Pull request by rdmdk**
Instead of bumping it every year

### CODE REVIEW

**Comment by eladnava** [comment]
@rdmdk Awesome, cheers 🎉 💯 . It's live!

**Comment by rdmdk** [comment]
@eladnava fantastic! have some ideas for other improvements but unsure how to implement (e.g. adding data-attributes to the html to indicate the webpage is being loaded inside an extension - not sure if that's even doable)

**Comment by rdmdk** [comment]
@eladnava I've applicationized a few of my own webapps and in some rare instances, they behaved differently. For example, on _window.prompt(a, b)_, _b_ does not display. If <html> were to be replaced by <html data-crx> or <html data-extension>, I could work around this or just omit that functionality entirely whenever the app loads inside of an extension.

**Comment by eladnava** [comment]
Unfortunately, that has to do with issue https://github.com/eladnava/applicationize/issues/36. There is no easy/clean way to resolve it unfortunately (but a workaround is mentioned in that issue).

**Comment by eladnava** [comment]
The workaround:
https://github.com/eladnava/applicationize/issues/25#issuecomment-250857260

**Comment by rdmdk** [comment]
Workaround: especially if your Applicationizing your own web apps:

URL:
https://exampleurl.com?crx

JS:
```
if (localStorage.crx) document.body.setAttribute('data-crx', '');
else if (window.location.href.includes('crx')) {
	localStorage.crx = true;
	window_location.href = '/'
}
```

**Pull request merged**
